### PR TITLE
Abstract in its own file

### PR DESCRIPTION
**Pull request by betatim**
The abstract now has its own file.

```
$ ./char-count.sh
proposal.md contains
   16103
characters
abstract.md contains
     300 abstract.md
words
```

We need to get rid of around 1000characters in the proposal or claim that these don't count as they are hyperlinks. Ideas?

### CODE REVIEW

**Comment by betatim** [comment]
Can we merge this before #87 to avoid conflicts? @ctb

**Comment by ctb** [comment]
sure, please go to town

**Comment by betatim** [comment]
You need to push the :radio_button:

**Comment by betatim** [comment]
:tada:

**Pull request merged**
