### PR TITLE
About Tim

### PR DESCRIPTION
**Pull request by betatim**
Short blurb about me.

Any thoughts on mentioning my ties to Moz with KT on the expert panel? I've tried my best not to use any MSL connections or meetings to promote this proposal.

### CODE REVIEW

**Comment by ctb** [comment]
What ties do you have with KT? In any case, I don't see any COIs in this proposal. We've avoided mentioning MSL or OSF in it, in particular.

**Comment by ctb** [comment]
Oh, I see. No problem IMO.

**Comment by ctb** [comment]
Shall I merge?

**Comment by betatim** [comment]
+1

**Pull request merged**
