### PR TITLE
Last minute fixes

### PR DESCRIPTION
**Pull request by betatim**
This PR implements mistakes noticed in #46 

(let's wait before merging this)

### CODE REVIEW

**Comment by betatim** [comment]
Thanks for the reproducible!

Just run ispell and it seems to be happy now. Except for remixability, that is apparently not a word yet.

**Comment by betatim** [comment]
Merge?

**Comment by khinsen** [comment]
LGTM!

**Comment by betatim** [comment]
You think we can get @ctb to press the :radio_button:?

**Comment by betatim** [comment]
Otherwise in the interest of getting this done, push it ;)

**Comment by khinsen** [comment]
OK. I'll leave one more minute for protests...

**Comment by khinsen** [comment]
:rocket:

**Comment by betatim** [comment]
I think he watches us from a distance :eyes:

**Comment by ctb** [comment]
my NSA feed alerts me to relevant messages

**Pull request merged**
