### PR TITLE
Adding to the Proposal

### PR DESCRIPTION
**Pull request by betatim**
Follow along as I work on the proposal. I'll update this message when it is ready for reviewing.

### CODE REVIEW

**Comment by betatim** [comment]
Thoughts and feedback welcome.

**Comment by betatim** [comment]
In particular on the order of the content and what is missing or should be removed. Let's do language/spelling/grammar comments when we have a better idea on the content

**Comment by betatim** [comment]
Need to update the LEP claim thumbdrive -> SSD/one laptop

**Comment by khinsen** [comment]
@betatim Is annotating via [hypothes.is](http://hypothes.is/) OK with you? In my experience that's way better for prose than GitHub discussion threads.

**Comment by betatim** [comment]
For discussing concrete changes in a PR I prefer comments directly on the line of the diff.

After merging this PR I was planning to do exactly what you propose! Circulate a link like https://via.hypothes.is/https://github.com/betatim/openscienceprize/blob/be9f0d577396c56de954e8dfacafe138fecb2ef5/proposal.md (this is a test I did with a friend yesterday night) which refers to a specific version to a few friends and fools to request comments. I think collecting all their comments in one place (even if we keep editing the document) on a fixed version is best.

(From my experience hypothes.is does an Ok job with changing documents, but not yet good enough for me to be brave enough to collect comments on a changing document)

**Comment by khinsen** [comment]
OK, I'll wait then until the PR is merged. My comments are not about specific changes, but about future changes to be made.

**Comment by betatim** [comment]
Merging in 3, 2, 1, ...

**Pull request merged**
