### PR TITLE
address proposal reqs

### PR DESCRIPTION
**Pull request by ctb**
tackle 'em head on, I always say.

I think we need to leave the bullet points in. all else, change at will!

### CODE REVIEW

**Comment by betatim** [comment]
Considering that we crossed the length limit a while ago I propose we start a one in, one out policy. What do we cut to fit this in?

:+1: on making it easy for the judges to find the answers to their judging questions.

**Comment by ctb** [comment]
On Mon, Feb 29, 2016 at 06:24:14AM -0800, Tim Head wrote:
> Considering that we crossed the length limit a while ago I propose we start a one in, one out policy. What do we cut to fit this in?
> 
> :+1: on making it easy for the judges to find the answers to their judging questions.

hey man, I just write text, I don't cut it :)

I vote we cut most of "who we are".

**Comment by betatim** [comment]
Who needs text generating RNNs if you have C. Titus Brown!

**Comment by betatim** [comment]
What do you think of moving all of the "who we are" into a separate file and the submitting that as one of the supplementary files?

**Comment by rougier** [comment]
If we move all URL at the end of the file, get rid of all the XXX and count characters (without URL then) the file still too large ?

**Comment by betatim** [comment]
@ctb I rebased this branch, which is tremendously evil given it isn't mine, is public, etc. I hope the git gods will forgive me.

With these changes applied we are now at:
```
proposal.md contains
   14816
characters
```
so I would recommend we merge.

**Comment by khinsen** [comment]
:+1:

**Comment by ctb** [comment]
Afk 

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by cranmer** [comment]
I’m trying to suggest some minor changes, but spending an hour dealing with git rebasing :-/

**Pull request merged**
