### PR TITLE
Renaming to everpub

### LINKED ISSUE #45: Renaming
@ctb suggested "everpub" as a name. Thoughts?

I like it, not only because it builds on the theme of everware.

### PR DESCRIPTION
**Pull request by betatim**
Changed the name to everpub as well as linking to `proposal-v2.md`

Fixes #45

### CODE REVIEW

**Comment by cranmer** [comment]
satyrn wept.

**Comment by ctb** [comment]
lol @cranmer - Satyrn can still be the name of a specific implementation, you know :)

**Comment by ctb** [comment]
@betatim propose merging this, renaming to proposal.md, transferring to Google Docs and opening up to comments and suggested edits. What do you say to any/all of that?

**Comment by betatim** [comment]
I'll add a commit renaming the file and then we can merge. See that other issue on my thoughts for gdocs.

**Comment by betatim** [comment]
Merge please

**Pull request merged**
