### PR TITLE
Split proposal into sections

### PR DESCRIPTION
**Pull request by betatim**
I will work on splitting things into sections. Currently thinking:

1. Summary
1. State of the art
1. Challenges/short comings
1. Our solution
1. Conclusion

### CODE REVIEW

**Comment by betatim** [comment]
Should add a paragraph or section for each of:

* [ ] Advancement of Open Science
* [x] Impact
* [ ] Innovation
* [ ] Originality
* [ ] Technological viability
* [ ] Resource feasibility

**Comment by betatim** [comment]
@JackDapid I have tried to incorporate your suggestions on the story. [Take a look](https://github.com/betatim/openscienceprize/blob/tim-proposal-sections/proposal.md) at the rendered markdown for easier reading.

The structure is now like this:

1. Summary
1. Story
1. Impact
  1. Short term user story
  1. Long term user story
  1. Social web of science story
1. State of the Art
1. Solution
1. Resource feasibility
1. Licenses
1. Conclusion

**Comment by betatim** [comment]
I would like to get this merged. It is already :balloon:ing and making it hard to write up thoughts from #16 in parallel.

Some feedback from @ctb or @JackDapid would be good on totally wrong/rubbish stuff. Otherwise I propose to merge, and then repair/improve as we go along.

**Comment by ctb** [comment]
merge!

**Comment by betatim** [comment]
Push the button :radio_button:

**Pull request merged**
