### PR TITLE
New logo idea

### PR DESCRIPTION
**Pull request by betatim**
We do need a logo for the submission. What do you think of this as a starting point? It is extremely simple ...

g3820

### CODE REVIEW

**Comment by betatim** [comment]
I've used this in the submission form for the moment. If we get a better proposal in time it is easy to swap.

**Comment by eamonnmag** [comment]
everpub-02

**Comment by rougier** [comment]
Gorgeous ! (P & U are a bit close)

**Comment by betatim** [comment]
Woah! Can you make it 200x200px (only a requirement for the submission and openscienceprize website)

I actually like it with all three of them in one picture.

**Comment by cranmer** [comment]
Dude!

**Comment by m3gan0** [comment]
@cranmer took the word outta my mouth. The last one is best for light BG, the first for dark BG. The The teal logo is too similar to Research Gate's for my liking (RG, eww).

**Comment by eamonnmag** [comment]
everpub-03
everpub-04
everpub-05

**Comment by eamonnmag** [comment]
Which one in 200px? They are all in 200px x 200px boundaries but are exported at 300 dpi.

**Comment by betatim** [comment]
My :+1: goes to [top one](https://cloud.githubusercontent.com/assets/282396/13402037/ccb2bb22-df0e-11e5-9881-185cf0332aa8.png).

**Comment by eamonnmag** [comment]
everpub-200px

**Comment by khinsen** [comment]
:+1: :+1: :+1:

**Comment by rougier** [comment]
@eamonnmag Would be great to include the png in the PR to be able to display it on github README.
(and get rid of the old logo by the way)

**Comment by eamonnmag** [comment]
I'm currently out. Can someone do it in my virtual absence? :)

**Pull request merged**
