### PR TITLE
The team is moving

### PR DESCRIPTION
**Pull request by betatim**
Following #87 the team is moving to its own file.

### CODE REVIEW

**Comment by betatim** [comment]
Next we merge this. Then rebase #87 and have a recount :us: election style

**Comment by ctb** [comment]
and just to be clear, you want me to do this merge? :)

**Comment by betatim** [comment]
Anyone who isn't me ;)

The contents of `team.md` is already in the application form. There is a whole section I filled in with the verbatim info from that file.

**Comment by betatim** [comment]
So I don't think we need to link it. What do you think?

**Comment by khinsen** [comment]
Perhaps not for the submission PDF, but for people reading the proposal here on GitHub, the link would help to find the material.

We can of course deal with that later.

**Comment by betatim** [comment]
We could add links to the team, the proposal and abstract in the README. :+1:

**Pull request merged**
