### PR TITLE
Moving day

### PR DESCRIPTION
**Pull request by betatim**
Think this catches all the links.

### CODE REVIEW

**Comment by khinsen** [comment]
Now we need to move to make the links work again!

**Comment by betatim** [comment]
Faster than the NSA!

**Comment by khinsen** [comment]
The NSA is limited by the speed of light. Can't beat me acting from Paris ;-)

**Comment by betatim** [comment]
:construction: :construction: :construction: entering the danger zone ... see you all on the other side! :construction: :construction: :construction:

**Comment by khinsen** [comment]
We made it!!!

**Comment by betatim** [comment]
Welcome back!

**Comment by lukasheinrich** [comment]
:+1:

**Pull request merged**
