### PR TITLE
Remove extraneous brackets

### PR DESCRIPTION
**Pull request by khinsen**

### CODE REVIEW

**Comment by betatim** [comment]
Why not keep the link? (this is what the PR is changing right?)

**Comment by cranmer** [comment]
see https://github.com/betatim/openscienceprize/pull/94  your call

**Comment by khinsen** [comment]
@betatim I kept your reference to `proponents.pdf` but removed @cranmer's link to the GitHub URL, which would be inappropriate in the PDF for submission. I just forgot to remove the brackets. Didn't we decide to move that to `README.md`? Which, of course, remains to be done - but it's less urgent than getting the submission done.

**Comment by betatim** [comment]
bof. We link directly to the repo and issues in it. So if they disqualify us for linking to stuff then they have lots of other reasons for doing so. I think as long as all the required material is also part of the submission we should be fine. My two cents.

**Comment by khinsen** [comment]
OK, so I put the link back in? That would be the occasion to link to the new `everpub` organization.

**Comment by betatim** [comment]
Let's add the link back in.

**Comment by betatim** [comment]
But for the moment leave it pointing to the old repo for the moment. Let's move the discussion of the link to #46

**Comment by khinsen** [comment]
This should be OK to merge now.

**Pull request merged**
