### PR TITLE
Remove all the XXXs

### PR DESCRIPTION
**Pull request by betatim**
This removes all the XXXs. I didn't have good ideas what to add in places where it called for more references, and given the length I think that is Ok.

If you have specific examples, post them here and I will add them.

### CODE REVIEW

**Comment by betatim** [comment]
The second commit addresses [@cranmer's comment](https://github.com/betatim/openscienceprize/issues/2#issuecomment-190213537) in #2

**Comment by betatim** [comment]
Fine to merge from my side.

**Comment by cranmer** [comment]
none by themself provides -> none by themselves provides

**Comment by cranmer** [comment]
seems easier to make comment to existing PR than try to make another.

I understand team got moved to a new file, but any reason there isn't a link or a reference?  
The "who we are" section is a little odd now given that the team has many strengths. 
I appreciate highlighting CTB and TH as US and European leads. Everware is directly relevant
to proposal. I'm not sure how relevant software carpentry is here.

**Comment by betatim** [comment]
Good point I'll add a sentence telling the reader that one of the supporting documents contains an exhaustive list of proponents.

For the github version we discussed with @khinsen to link all the documents directly from the `README`.

Can you make a proposal for what would be a better paragraph for the "who we are" section?

I will be offline from now till after the 8pm deadline. So probably the best way to progress is to merge this and continue in a new PR.

**Comment by cranmer** [comment]
sounds good to me. I notice CTB and TH are called proponents, but not in the team.md file

**Comment by betatim** [comment]
`team.md` was mainly a crutch for bureaucracy to collect the info needed to fill in the form for OSP. I had bugged CTB by email previously and knew the answers for TH ;)

**Comment by cranmer** [comment]
see #97. Rewords text for @betatim and @ctb (hopefully in a flattering way that is relevant to the proposal). It points to proponents.md with the full url so that the link should work in rendered pdf.

**Comment by khinsen** [comment]
@cranmer I will merge this first and than adapt #97 - we won't ask you to rebase all the time!

**Comment by cranmer** [comment]
Thanks for doing leg work. Above @betatim  wrote "Good point I'll add a sentence telling the reader that one of the supporting documents contains an exhaustive list of proponents."  Not exactly the same, but I thought this link would satisfy that.

**Comment by khinsen** [comment]
@cranmer We have to submit PDFs. Putting a link to GitHub into such a PDF could be seen as cheating by referring to non-submitted material.

**Comment by cranmer** [comment]
ok. Note the who we are has "The [proponents] " so need to remove the brackets

**Comment by cranmer** [comment]
while you are at it, please add http://www.researchobject.org in the related projects.

**Comment by khinsen** [comment]
That's #100. Someone else will have to push the button, according to our single rule.

**Pull request merged**
